resources:
# All RBAC will be applied under this service account in
# the deployment namespace.
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
# Roles for the CRD
- podmailer_editor_role.yaml
- podmailer_viewer_role.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

