# permissions for end users to view podmailers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: my-operator
    app.kubernetes.io/managed-by: kustomize
  name: podmailer-viewer-role
rules:
- apiGroups:
  - podmailer.podmailer.io
  resources:
  - podmailers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - podmailer.podmailer.io
  resources:
  - podmailers/status
  verbs:
  - get
